name: Dockerfile Linter

on:
  pull_request:
    branches: [ "main" ]

jobs:
  dockerfile-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Dockerfile lint
      # https://github.com/hadolint/hadolint
      # TODO: find better alternatives?
      # Do no fail the workflow on linter error at initial phase, will update this workflow later
      run: docker run --rm -i hadolint/hadolint < Dockerfile || true
