name: Scans container images
on:
  schedule:
    - cron: '0 0 */14 * 6' # Run every 14 days on Saturday at midnight
  workflow_dispatch:
jobs:
  build:
    name: Scan
    runs-on: ubuntu-24.04
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: 'tungbq/devops-toolkit:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
